# Escalate any statement-terminating error to a script-terminating one.
trap { break }


function CompareFiles(
	[string] $leftPath,
	[string] $rightPath,
	[int] $bufferSize = 0x4000 )
{
	if ( $bufferSize -le 0 )
	{
		throw "Invalid buffer size"
	}

	$leftFile  = new-object IO.FileInfo (resolve-path $leftPath)
	$rightFile = new-object IO.FileInfo (resolve-path $rightPath)

	if ( !$leftFile.Exists -or !$rightFile.Exists -or ($leftFile.Length -ne $rightFile.Length) )
	{
		return $false
	}

	$leftBuf  = new-object byte[] $bufferSize
	$rightBuf = new-object byte[] $bufferSize

	try
	{
		$leftStream  = $leftFile.OpenRead()
		$rightStream = $rightFile.OpenRead()

		do
		{
			$bytesRead = $leftStream.Read( $leftBuf, 0, $bufferSize )
			[void] $rightStream.Read( $rightBuf, 0, $bufferSize )

			for ( $i = 0; $i -lt $bytesRead; $i++ )
			{
				if ( $leftBuf[$i] -ne $rightBuf[$i] )
				{
					return $false
				}
			}
		}
		while ( $bytesRead -eq $bufferSize )
	}
	finally
	{
		$leftStream.Close()
		$rightStream.Close()
	}

	return $true
}

function CompareBinaryFiles( $left, $right )
{
	write-host "Comparing $left and $right..."
	return CompareFiles $left $right
}

function CompareAgainstKnownCheckSum( $newFile, $knownCheckSum )
{
	write-host "$origFile not found; comparing against known hash..."
	write-host "`tOld MD5: $knownCheckSum"
	$newMD5 = (Get-FileHash -Path $newFile -Algorithm MD5).Hash
	Write-Host "`tNew MD5: $newMD5"

	return $newMD5 -eq $knownCheckSum
}


echo "Assembling..."

# entry.asm - the "main" assembly file that pulls in our header and code/data for each bank
# layout - linker config file generated by da65ify; defines memory areas and segments
cc65\ca65 LegacyOfTheWizard.asm

echo "Linking..."

$outputFile = "LegacyOfTheWizard.nes"
cc65\ld65 -C memory.cfg -o $outputFile LegacyOfTheWizard.o

$origFile = "original.nes"	

# if original.nes ROM exists, compare against its MD5
if (test-path -path $origFile) {
	# Can compare file contents if old one present	
	if ( CompareBinaryFiles $origFile $outputFile ) {
		Write-Host "`tROMs match!" -ForegroundColor Blue
		$newMD5 = (Get-FileHash -Path $outputFile -Algorithm MD5).Hash
		Write-Host "`tMD5: $newMD5" -ForegroundColor Blue
	}
	else {
		Write-Host "`tROM mismatch! See Diff below:" -ForegroundColor Red
		fc.exe /b $outputFile $origFile
		Write-Host "" -ForegroundColor Red	
	}
}

# If we don't have the original ROM itself, can at least compare against a known hash
else {
	$knownCheckSum = "DC2075DE098C136D6B8EE43477164045"
	if (CompareAgainstKnownCheckSum $outputFile $knownCheckSum ) {
		Write-Host "`tMD5's match!" -ForegroundColor Blue
	} else {
		Write-Host "`tMD5 mismatch! Check source files for errors." -ForegroundColor Red
	}
}